// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/med-master-ai/AIDoubtSolver.tsx": () => import("../components/mockups/med-master-ai/AIDoubtSolver.tsx"),
  "./components/mockups/med-master-ai/Dashboard.tsx": () => import("../components/mockups/med-master-ai/Dashboard.tsx"),
  "./components/mockups/med-master-ai/Flashcards.tsx": () => import("../components/mockups/med-master-ai/Flashcards.tsx"),
  "./components/mockups/med-master-ai/QuizSection.tsx": () => import("../components/mockups/med-master-ai/QuizSection.tsx"),
  "./components/mockups/med-master-ai/SignIn.tsx": () => import("../components/mockups/med-master-ai/SignIn.tsx"),
  "./components/mockups/med-master-ai/SignUp.tsx": () => import("../components/mockups/med-master-ai/SignUp.tsx"),
  "./components/mockups/med-master-ai/Subjects.tsx": () => import("../components/mockups/med-master-ai/Subjects.tsx"),
  "./components/mockups/med-master-ai/Subscription.tsx": () => import("../components/mockups/med-master-ai/Subscription.tsx")
};
